version: '2'
services:
   shopserivce:
       container_name: shopserivce-1
       build:
          context: .
          dockerfile: Dockerfile
       restart: always
       ports:
       - "8007:8007"
       volumes:
       - ../target/ShopService.jar:/root/target/ShopService.jar
       networks:
       - java110-net
#       mem_limit: 1024m
       extra_hosts:
       - "dev.java110.com:172.31.35.145"
       - "dev.db.java110.com:172.31.35.145"
       - "dev.zk.java110.com:172.31.35.145"
       - "dev.kafka.java110.com:172.31.35.145"
       - "dev.redis.java110.com:172.31.35.145"
       - "api.java110.com:172.31.35.145"
networks:
  java110-net:
    external: true